services:
  - type: web
    name: business-search
    env: python
    buildCommand: pip install -r requirements.txt && python -m playwright install
    startCommand: gunicorn main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        generateValue: true
    plan: free 