services:
  - type: web
    name: business-search
    env: python
    buildCommand: |
      pip install -r requirements.txt && \
      playwright install chromium && \
      playwright install-deps
    startCommand: gunicorn main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "/opt/render/.cache/ms-playwright"
    plan: free 