services:
  - type: web
    name: webscrapy
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
      python -m playwright install-deps
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
      - key: GUNICORN_CMD_ARGS
        value: --workers=1 --threads=1 --timeout=120
      - key: PORT
        value: 10000
    plan: free 